  SELECT T1.EMPLOYEE_ID,
         SUM (
            ROUND (MONTHS_BETWEEN (TO_DATE (END_DATE), TO_DATE (START_DATE))))
            AS "MESES",
         T2."COUNT"
    FROM    JOB_HISTORY T1
         INNER JOIN
            (  SELECT EMPLOYEE_ID, COUNT (JOB_ID) AS "COUNT"
                 FROM JOB_HISTORY
             GROUP BY EMPLOYEE_ID) T2
         ON (T1.EMPLOYEE_ID = T2.EMPLOYEE_ID)
GROUP BY T1.EMPLOYEE_ID, T2."COUNT"
