-- O conceito deste exercicio era o não agrupamento de todos os campo... resolvido fazendo um self join
  SELECT T1.EMPLOYEE_ID,
         SUM (
            ROUND (MONTHS_BETWEEN (TO_DATE (END_DATE), TO_DATE (START_DATE))))
            AS "MESES",
            SUM(ROUND (MONTHS_BETWEEN (TO_DATE (END_DATE), TO_DATE (START_DATE))/12,1)) AS "ANOS E MESES",
            T2."QTD_JOBS"
    FROM    JOB_HISTORY T1
         INNER JOIN
            (  SELECT EMPLOYEE_ID, COUNT (JOB_ID) AS "QTD_JOBS"
                 FROM JOB_HISTORY
             GROUP BY EMPLOYEE_ID) T2
         ON (T1.EMPLOYEE_ID = T2.EMPLOYEE_ID)
GROUP BY T1.EMPLOYEE_ID, T2."QTD_JOBS"
  

--Pegar o nome do funcionario que é manager. conceito... self join e verificar os managers da tabela 1 que são funcionarios da tabela 2
SELECT FIRST_NAME || ' ' || LAST_NAME AS "EMPLOYEE_NAME", T2."MANAGER_NAME",T1.MANAGER_ID
  FROM    EMPLOYEES T1
       LEFT JOIN
          (SELECT FIRST_NAME || ' ' || LAST_NAME AS "MANAGER_NAME", EMPLOYEE_ID
             FROM EMPLOYEES
            WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID FROM EMPLOYEES)) T2
       ON  T1.MANAGER_ID = T2.EMPLOYEE_ID 
       ORDER BY 1
SET UNDERLINE '='
SET COLSEP '|'
COLUMN "MODULO" FORMAT A30 
COLUMN "VERSAO" FORMAT A30
SELECT 
	F.MODULO MODULO,
	NVL(G.VER_VERSAO,'<<SISTEMA NÃO INSTALADO!>>') VERSAO
	FROM(
		SELECT 1 ORDEM, 'MANAGER' 		MODULO FROM DUAL UNION ALL 
		SELECT 2 ORDEM, 'NFE'	  		MODULO FROM DUAL UNION ALL 
		SELECT 3 ORDEM, 'EFD'	  		MODULO FROM DUAL UNION ALL 
		SELECT 4 ORDEM, 'ECD' 	  		MODULO FROM DUAL UNION ALL 
		SELECT 5 ORDEM, 'ECF' 	    	MODULO FROM DUAL UNION ALL 
		SELECT 6 ORDEM, 'HOSPITALAR' 	MODULO FROM DUAL UNION ALL 
		SELECT 7 ORDEM, 'SISCOSERV' 	MODULO FROM DUAL
	)F
	LEFT JOIN 
	(
		SELECT 'MANAGER' SISTEMA, VER_VERSAO FROM (
			SELECT VER_VERSAO FROM VERSAO_VER WHERE VER_VERSAO LIKE '%8.%' AND ROWNUM = 1 ORDER BY VER_DATA DESC 
		)UNION 
		SELECT 'NFE' SISTEMA, VER_VERSAO FROM(
			SELECT VER_VERSAO FROM VERSAO_VER WHERE VER_VERSAO LIKE '%NFE%' AND ROWNUM = 1 ORDER BY VER_DATA DESC 
		)UNION 
		SELECT 'EFD' SISTEMA, VER_VERSAO FROM(
			SELECT VER_VERSAO FROM VERSAO_VER WHERE VER_VERSAO LIKE '%EFD%' AND ROWNUM = 1 ORDER BY VER_DATA DESC 
		)UNION 
		SELECT 'ECD' SISTEMA, VER_VERSAO FROM(
			SELECT VER_VERSAO FROM VERSAO_VER WHERE VER_VERSAO LIKE '%ECD%' AND ROWNUM = 1 ORDER BY VER_DATA DESC 
		)UNION 
		SELECT 'ECF' SISTEMA, VER_VERSAO FROM(
			SELECT VER_VERSAO FROM VERSAO_VER WHERE VER_VERSAO LIKE '%ECF%' AND ROWNUM = 1 ORDER BY VER_DATA DESC 
		)UNION
		SELECT 'HOSPITALAR' SISTEMA, VER_VERSAO FROM(
			SELECT VER_VERSAO FROM VERSAO_VER WHERE VER_VERSAO LIKE '%HOSPT%' OR VER_VERSAO LIKE '%HOSPT9%' AND ROWNUM = 1 ORDER BY VER_DATA DESC 
		)UNION 
		SELECT 'SISCOSERV' SISTEMA, VER_VERSAO FROM(
			SELECT VER_VERSAO FROM VERSAO_VER WHERE VER_VERSAO LIKE '%SISCOSERV%' AND ROWNUM = 1 ORDER BY VER_DATA DESC 
		)
	)G ON F.MODULO = G.SISTEMA;
