SET LINES 800
SET DEFINE OFF
SET COLSEP '|'
SET UNDERLINE '='
SET PAGES 100
SPOOL LEVANTAMENTO_LOG.LOG
PROMPT *******************************************************************
PROMPT *       LEVANTAMENTO DE INFORMAÇÕES DO SERVIDOR DE BD             *
PROMPT *                            [V1.0]                               *
PROMPT *******************************************************************
SELECT 	'USUÁRIO_ORACLE| ' ||SYS_CONTEXT('USERENV','SESSION_USER') ||CHR(10)||
		'INSTANCIA.....| ' ||SYS_CONTEXT('USERENV','INSTANCE_NAME')||CHR(10)|| 
		'USUARIO S.O...| ' ||SYS_CONTEXT('USERENV','OS_USER')      ||CHR(10)||
		'SERVIDOR......| ' ||SYS_CONTEXT('USERENV','HOST')         ||CHR(10)||
		'DATA/HORA.....| ' ||TO_CHAR(TO_DATE(SYSDATE),'DD/MM/YYYY HH24:MI:SS') ||CHR(10) AS "INFORMAÇÕES DE CONEXÃO"
		FROM DUAL; 
--select SYS_CONTEXT('USERENV','IP_ADDRESS') from dual;
PROMPT *******************************************************************
PROMPT *                      VERSÃO ORACLE                              *
PROMPT ******************************************************************* 
SELECT BANNER FROM v$version;		
		

PROMPT *******************************************************************
PROMPT *                      TAMANHO TABLESPACES                        *
PROMPT ******************************************************************* 
SELECT  NVL(D.TABLESPACE_NAME,'TOTAL') AS "NOME_TABLESPACE",            
        TO_CHAR(SUM(((A.BYTES - DECODE(F.BYTES, NULL, 0, F.BYTES)) / 1024 / 1024)),'FM999G999G9999G990D00') AS "TAMANHO_USADO(MB)"            
FROM    SYS.DBA_TABLESPACES D,
        SYS.SM$TS_AVAIL A, 
        SYS.SM$TS_FREE F
WHERE   D.TABLESPACE_NAME = A.TABLESPACE_NAME 
AND     F.TABLESPACE_NAME (+) = D.TABLESPACE_NAME
GROUP BY    ROLLUP(D.TABLESPACE_NAME);


PROMPT *******************************************************************
PROMPT *                      TAMANHO FISICO TABLESPACES                 *
PROMPT ******************************************************************* 
COLUMN "TABLESPACE_NAME"  		FORMAT A14
COLUMN "STATUS"					FORMAT A14
COLUMN "SPACE_USED(MB)"  		FORMAT A14
COLUMN "MAX_SIZE(MB)" 			FORMAT A14
COLUMN "SPACE_FREE(MB)"			FORMAT A14
COLUMN "PCT_USED(%)" 			FORMAT A14
SELECT 	DTU.TABLESPACE_NAME, DT.STATUS,
		TO_CHAR(ROUND((USED_SPACE*8192 / 1048576),2),'FM999G999G9999G990D00') AS "SPACE_USED(MB)",
		TO_CHAR(ROUND((TABLESPACE_SIZE*8192/1048576),2),'FM999G999G9999G990D00') AS "MAX_SIZE(MB)",
		TO_CHAR(ROUND((TABLESPACE_SIZE*8192/1048576),2) - ROUND((USED_SPACE*8192/1048576),2),'FM999G999G9999G990D00') AS "SPACE_FREE(MB)",
		TO_CHAR(ROUND((USED_PERCENT* 8192 / 1048576)*100,2),'FM999G999G9999G990D00')||'%' AS "PCT_USED(%)"
FROM DBA_TABLESPACE_USAGE_METRICS DTU
INNER JOIN DBA_TABLESPACES DT 
ON DTU.TABLESPACE_NAME = DT.TABLESPACE_NAME
ORDER BY 1;


PROMPT *******************************************************************
PROMPT *                      INFO. DATAFILES                            *
PROMPT ******************************************************************* 
COLUMN "FILE_NAME"		 FORMAT A80 
COLUMN "TABLESPACE_NAME" FORMAT A15 
COLUMN "TAMANHO(MB)" 	 FORMAT A20 
COLUMN "STATUS" 		 FORMAT A18 
COLUMN "ONLINE_STATUS" 	 FORMAT A20
SELECT 	FILE_NAME,
		TABLESPACE_NAME,
		TO_CHAR(TO_NUMBER(BYTES/1024/1024),'FM999G999G9999G990D00') "TAMANHO(MB)",
		STATUS,ONLINE_STATUS 
FROM DBA_DATA_FILES 
ORDER BY TABLESPACE_NAME;



PROMPT *******************************************************************
PROMPT *		           INFO. TAMANHO OWNER                           * --revisar 
PROMPT *******************************************************************
COLUMN "OWNER" 				FORMAT A20
COLUMN "TABLESPACE_PADRAO"	FORMAT A30 
COLUMN "TAMANHO"		 	FORMAT A20 

SELECT 	NVL(C.OWNER,'[TOTAL]') AS "OWNER",
		NVL(C.TABLESPACE_NAME,'[TOTAL]') AS "TABLESPACE_PADRAO",
       CASE
          WHEN C.BYTES < 1 	  THEN ROUND (C.BYTES * 1024, 2) || ' KB '
          WHEN C.BYTES < 1024 THEN ROUND (C.BYTES, 2) 		 || ' MB '
          ELSE ROUND (C.BYTES / 1024, 2) 	|| ' GB '
       END AS "TAMANHO"
  FROM (SELECT   OWNER AS OWNER, TABLESPACE_NAME AS TABLESPACE_NAME,
                 SUM (BYTES / 1024 / 1024) AS BYTES
            FROM DBA_SEGMENTS
        GROUP BY ROLLUP(OWNER, TABLESPACE_NAME)
        ORDER BY OWNER, TABLESPACE_NAME ASC) C

		
		
PROMPT *******************************************************************
PROMPT *                      USUARIOS BD                                *
PROMPT ******************************************************************* 
SELECT 	USERNAME, 
		USER_ID,
		CREATED
		FROM ALL_USERS DU
		ORDER BY USERNAME;


PROMPT *******************************************************************
PROMPT *                      MEMORIA FISICA(SGA)                        *
PROMPT ******************************************************************* 
   SELECT NAME, 
	   DISPLAY_VALUE 
FROM V$PARAMETER 
WHERE NAME IN('sga_target');


PROMPT *******************************************************************
PROMPT *                         INFO GERAIS PFILE                       *
PROMPT ******************************************************************* 
SELECT 
	PARAMETRO.NOME "PARAMETRO", 
	NVL(VALOR.DISPLAY_VALUE,'<<N Parametrizado>>') "VALOR", 
	PARAMETRO.DESCRICAO "DESCRICAO"
	FROM (SELECT 1 ORDEM,  'OPEN_CURSORS'        		NOME,'Cursors and Library Cache'  DESCRICAO FROM DUAL UNION 
		  SELECT 2 ORDEM,  'DB_BLOCK_SIZE'         		NOME,'Cache and I/O'  DESCRICAO FROM DUAL UNION 
		  SELECT 3 ORDEM,  'PGA_AGGREGATE_TARGET'  		NOME,'Sort, Hash Joins, Bitmap Indexes'  DESCRICAO FROM DUAL UNION
		  SELECT 4 ORDEM,  'DB_CREATE_FILE_DEST'   		NOME,'File Configuration'  DESCRICAO FROM DUAL UNION 
		  SELECT 5 ORDEM,  'DB_RECOVERY_FILE_DEST' 		NOME,'File Configuration'  DESCRICAO FROM DUAL UNION
		  SELECT 6 ORDEM,  'DB_RECOVERY_FILE_DEST_SIZE' NOME,'File Configuration'  DESCRICAO FROM DUAL UNION  
		  SELECT 7 ORDEM,  'COMPATIBLE' 				NOME,'Miscellaneous'  DESCRICAO FROM DUAL UNION 
		  SELECT 8 ORDEM,  'DIAGNOSTIC_DEST' 			NOME,'Miscellaneous'  DESCRICAO FROM DUAL UNION
		  SELECT 9 ORDEM,  'DB_DOMAIN' 					NOME,'Database Identification'  DESCRICAO FROM DUAL UNION 
		  SELECT 10 ORDEM, 'DB_NAME' 					NOME,'Database Identification'  DESCRICAO FROM DUAL UNION  
		  SELECT 11 ORDEM, 'SGA_TARGET' 				NOME,'SGA Memory'  DESCRICAO FROM DUAL UNION 
		  SELECT 12 ORDEM, 'PROCESSES' 					NOME,'Processes and Sessions'  DESCRICAO FROM DUAL UNION 
		  SELECT 13 ORDEM, 'SESSIONS' 					NOME,'Processes and Sessions'  DESCRICAO FROM DUAL UNION 
		  SELECT 14 ORDEM, 'UNDO_TABLESPACE' 			NOME,'System Managed Undo and Rollback Segments'  DESCRICAO FROM DUAL UNION 
		  SELECT 15 ORDEM, 'AUDIT_FILE_DEST' 			NOME,'Security and Auditing'  DESCRICAO FROM DUAL UNION 
		  SELECT 16 ORDEM, 'AUDIT_TRAIL' 				NOME,'Security and Auditing'  DESCRICAO FROM DUAL UNION 
		  SELECT 17 ORDEM, 'REMOTE_LOGIN_PASSWORDFILE' 	NOME,'Security and Auditing'  DESCRICAO FROM DUAL UNION 
		  SELECT 18 ORDEM, 'DISPATCHERS' 				NOME,'Shared Server'  DESCRICAO FROM DUAL UNION 
		  SELECT 19 ORDEM, 'CONTROL_FILES' 				NOME,'Shared Server'  DESCRICAO FROM DUAL  
		  ) PARAMETRO
		  LEFT JOIN
		  (SELECT 'OPEN_CURSORS' NAME, DISPLAY_VALUE 
		  FROM (SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='open_cursors')
		  UNION
		  SELECT 'DB_BLOCK_SIZE' NAME, DISPLAY_VALUE
		  FROM (SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='db_block_size')
		  UNION 
		  SELECT 'PGA_AGGREGATE_TARGET' NAME, DISPLAY_VALUE 
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='pga_aggregate_target')
		  UNION 
		  SELECT 'DB_CREATE_FILE_DEST' NAME, DISPLAY_VALUE 
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='db_create_file_dest')
		  UNION 
		  SELECT 'DB_RECOVERY_FILE_DEST' NAME,DISPLAY_VALUE 
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='db_recovery_file_dest')
		  UNION 
		  SELECT 'DB_RECOVERY_FILE_DEST_SIZE' NAME, DISPLAY_VALUE
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='db_recovery_file_dest_size')
		  UNION 
		  SELECT 'COMPATIBLE' NAME, DISPLAY_VALUE 
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='compatible')
		  UNION 
		  SELECT 'DIAGNOSTIC_DEST' NAME, DISPLAY_VALUE
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='diagnostic_dest')
		  UNION 
		  SELECT 'DB_DOMAIN' NAME, DISPLAY_VALUE 
		  FROM (SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME ='db_domain')
		  UNION 
		  SELECT 'DB_NAME' NAME, DISPLAY_VALUE 
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='db_name')
		  UNION 
		  SELECT 'SGA_TARGET' NAME, DISPLAY_VALUE 
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='sga_target')
		  UNION 
		  SELECT 'PROCESSES' NAME, DISPLAY_VALUE
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='processes')
		  UNION
		  SELECT 'SESSIONS' NAME, DISPLAY_VALUE
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='sessions')
		  UNION 
		  SELECT 'UNDO_TABLESPACE' NAME, DISPLAY_VALUE
		  FROM(SELECT  DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='undo_tablespace')
		  UNION 
		  SELECT 'AUDIT_FILE_DEST' NAME, DISPLAY_VALUE
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='audit_file_dest')
		  UNION
		  SELECT 'AUDIT_TRAIL' NAME, DISPLAY_VALUE
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='audit_trail')
		  UNION 
		  SELECT 'REMOTE_LOGIN_PASSWORDFILE' NAME, DISPLAY_VALUE
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='remote_login_passwordfile')
		  UNION 
		  SELECT 'DISPATCHERS' NAME, DISPLAY_VALUE 
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME ='dispatchers')
		  UNION
		  SELECT 'CONTROL_FILES' NAME, DISPLAY_VALUE 
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='control_files')
		  )VALOR ON PARAMETRO.NOME = VALOR.NAME 
		  ORDER BY PARAMETRO.ORDEM; J  
   
PROMPT *******************************************************************
PROMPT *                      PARAMETROS INSTANCIA                       *
PROMPT *******************************************************************  
SELECT * FROM V$INSTANCE; 
   
PROMPT *******************************************************************
PROMPT *                      PARAMETROS DATABASE                        *
PROMPT *******************************************************************    
SELECT * FROM V$DATABASE;
SPOOL OFF 


SELECT 
	TABLESPACE_NAME,ROUND(USED_SPACE/1024/1024,2), 
	ROUND(TABLESPACE_SIZE/1024/1024,2),
	ROUND(USED_PERCENT/1024/1024,2), 
	ROUND(USED_SPACE/TABLESPACE_SIZE*100,2) 
FROM DBA_tABLESPACE_USAGE_METRICS;
   

 SELECT
 TABLESPACE_NAME,ROUND(USED_SPACE/1024,2),
 ROUND(TABLESPACE_SIZE/1024,2),
 ROUND(USED_PERCENT/1024,2), 
 ROUND(USED_SPACE/TABLESPACE_SIZE*100,2) 
 FROM DBA_tABLESPACE_USAGE_METRICS   
   
   

Memoria instalada: 32GB 
HD: 1861,2GB 
Intel(R) Xeon(R) CPU E5-2407 0 @ 2.20GHz 
Microsoft Windows Server 2012 R2 Standard 

C: 214GB / 
USADO:156  
LIVRE: 58,2  

D: 1,60TB / 
USADO: 1,34TB  g
LIVRE: 269GB 


SELECT 
	PARAMETRO.NOME "PARAMETRO", 
	NVL(VALOR.DISPLAY_VALUE,'<<N Parametrizado>>') "VALOR", 
	PARAMETRO.DESCRICAO "DESCRICAO"
	FROM (SELECT 1 ORDEM,  'OPEN_CURSORS'        		NOME,'Cursors and Library Cache'  DESCRICAO FROM DUAL UNION 
		  SELECT 2 ORDEM,  'DB_BLOCK_SIZE'         		NOME,'Cache and I/O'  DESCRICAO FROM DUAL UNION 
		  SELECT 3 ORDEM,  'PGA_AGGREGATE_TARGET'  		NOME,'Sort, Hash Joins, Bitmap Indexes'  DESCRICAO FROM DUAL UNION
		  SELECT 4 ORDEM,  'DB_CREATE_FILE_DEST'   		NOME,'File Configuration'  DESCRICAO FROM DUAL UNION 
		  SELECT 5 ORDEM,  'DB_RECOVERY_FILE_DEST' 		NOME,'File Configuration'  DESCRICAO FROM DUAL UNION
		  SELECT 6 ORDEM,  'DB_RECOVERY_FILE_DEST_SIZE' NOME,'File Configuration'  DESCRICAO FROM DUAL UNION  
		  SELECT 7 ORDEM,  'COMPATIBLE' 				NOME,'Miscellaneous'  DESCRICAO FROM DUAL UNION 
		  SELECT 8 ORDEM,  'DIAGNOSTIC_DEST' 			NOME,'Miscellaneous'  DESCRICAO FROM DUAL UNION
		  SELECT 9 ORDEM,  'DB_DOMAIN' 					NOME,'Database Identification'  DESCRICAO FROM DUAL UNION 
		  SELECT 10 ORDEM, 'DB_NAME' 					NOME,'Database Identification'  DESCRICAO FROM DUAL UNION  
		  SELECT 11 ORDEM, 'SGA_TARGET' 				NOME,'SGA Memory'  DESCRICAO FROM DUAL UNION 
		  SELECT 12 ORDEM, 'PROCESSES' 					NOME,'Processes and Sessions'  DESCRICAO FROM DUAL UNION 
		  SELECT 13 ORDEM, 'SESSIONS' 					NOME,'Processes and Sessions'  DESCRICAO FROM DUAL UNION 
		  SELECT 14 ORDEM, 'UNDO_TABLESPACE' 			NOME,'System Managed Undo and Rollback Segments'  DESCRICAO FROM DUAL UNION 
		  SELECT 15 ORDEM, 'AUDIT_FILE_DEST' 			NOME,'Security and Auditing'  DESCRICAO FROM DUAL UNION 
		  SELECT 16 ORDEM, 'AUDIT_TRAIL' 				NOME,'Security and Auditing'  DESCRICAO FROM DUAL UNION 
		  SELECT 17 ORDEM, 'REMOTE_LOGIN_PASSWORDFILE' 	NOME,'Security and Auditing'  DESCRICAO FROM DUAL UNION 
		  SELECT 18 ORDEM, 'DISPATCHERS' 				NOME,'Shared Server'  DESCRICAO FROM DUAL UNION 
		  SELECT 19 ORDEM, 'CONTROL_FILES' 				NOME,'Shared Server'  DESCRICAO FROM DUAL  
		  ) PARAMETRO
		  LEFT JOIN
		  (SELECT 'OPEN_CURSORS' NAME, DISPLAY_VALUE 
		  FROM (SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='open_cursors')
		  UNION
		  SELECT 'DB_BLOCK_SIZE' NAME, DISPLAY_VALUE
		  FROM (SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='db_block_size')
		  UNION 
		  SELECT 'PGA_AGGREGATE_TARGET' NAME, DISPLAY_VALUE 
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='pga_aggregate_target')
		  UNION 
		  SELECT 'DB_CREATE_FILE_DEST' NAME, DISPLAY_VALUE 
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='db_create_file_dest')
		  UNION 
		  SELECT 'DB_RECOVERY_FILE_DEST' NAME,DISPLAY_VALUE 
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='db_recovery_file_dest')
		  UNION 
		  SELECT 'DB_RECOVERY_FILE_DEST_SIZE' NAME, DISPLAY_VALUE
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='db_recovery_file_dest_size')
		  UNION 
		  SELECT 'COMPATIBLE' NAME, DISPLAY_VALUE 
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='compatible')
		  UNION 
		  SELECT 'DIAGNOSTIC_DEST' NAME, DISPLAY_VALUE
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='diagnostic_dest')
		  UNION 
		  SELECT 'DB_DOMAIN' NAME, DISPLAY_VALUE 
		  FROM (SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME ='db_domain')
		  UNION 
		  SELECT 'DB_NAME' NAME, DISPLAY_VALUE 
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='db_name')
		  UNION 
		  SELECT 'SGA_TARGET' NAME, DISPLAY_VALUE 
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='sga_target')
		  UNION 
		  SELECT 'PROCESSES' NAME, DISPLAY_VALUE
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='processes')
		  UNION
		  SELECT 'SESSIONS' NAME, DISPLAY_VALUE
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='sessions')
		  UNION 
		  SELECT 'UNDO_TABLESPACE' NAME, DISPLAY_VALUE
		  FROM(SELECT  DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='undo_tablespace')
		  UNION 
		  SELECT 'AUDIT_FILE_DEST' NAME, DISPLAY_VALUE
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='audit_file_dest')
		  UNION
		  SELECT 'AUDIT_TRAIL' NAME, DISPLAY_VALUE
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='audit_trail')
		  UNION 
		  SELECT 'REMOTE_LOGIN_PASSWORDFILE' NAME, DISPLAY_VALUE
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='remote_login_passwordfile')
		  UNION 
		  SELECT 'DISPATCHERS' NAME, DISPLAY_VALUE 
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME ='dispatchers')
		  UNION
		  SELECT 'CONTROL_FILES' NAME, DISPLAY_VALUE 
		  FROM(SELECT DISPLAY_VALUE FROM V$PARAMETER WHERE NAME='control_files')
		  )VALOR ON PARAMETRO.NOME = VALOR.NAME 
		  ORDER BY PARAMETRO.ORDEM; 



nls_language


-- O conceito deste exercicio era o não agrupamento de todos os campo... resolvido fazendo um self join
  SELECT T1.EMPLOYEE_ID,
         SUM (
            ROUND (MONTHS_BETWEEN (TO_DATE (END_DATE), TO_DATE (START_DATE))))
            AS "MESES",
            SUM(ROUND (MONTHS_BETWEEN (TO_DATE (END_DATE), TO_DATE (START_DATE))/12,1)) AS "ANOS E MESES",
            T2."QTD_JOBS"
    FROM    JOB_HISTORY T1
         INNER JOIN
            (  SELECT EMPLOYEE_ID, COUNT (JOB_ID) AS "QTD_JOBS"
                 FROM JOB_HISTORY
             GROUP BY EMPLOYEE_ID) T2
         ON (T1.EMPLOYEE_ID = T2.EMPLOYEE_ID)
GROUP BY T1.EMPLOYEE_ID, T2."QTD_JOBS"
