CREATE OR REPLACE FUNCTION ADMDADOS_MAPEIA_TABELA(TABLE_NAME2 VARCHAR2)
 RETURN VARCHAR2
IS 
	NM_TABELA VARCHAR2(50); 
	V_CONSTRAINT_R VARCHAR2(50); 
	
BEGIN
	FOR CTS IN (SELECT   LEVEL,CONSTRAINT_NAME,R_CONSTRAINT_NAME
				FROM USER_CONS_COLUMNS UCC 
				INNER JOIN USER_CONSTRAINTS UC USING(CONSTRAINT_NAME)				
				WHERE UC.CONSTRAINT_TYPE = 'R' 
                START WITH UCC.TABLE_NAME=TABLE_NAME2 CONNECT BY PRIOR R_CONSTRAINT_NAME=CONSTRAINT_NAME)
				LOOP 
					V_CONSTRAINT_R := CTS.R_CONSTRAINT_NAME;
					
					SELECT TABLE_NAME INTO NM_TABELA  FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME=V_CONSTRAINT_R;
					
					DBMS_OUTPUT.PUT_LINE(NM_TABELA);
				END LOOP; 
	
	RETURN 'RETURN';
END; 
/
