SELECT DISTINCT TYPE||' '||NAME  FROM USER_SOURCE WHERE (NAME, TYPE) IN
(SELECT DISTINCT NAME, TYPE 
FROM USER_SOURCE 
WHERE (UPPER(TEXT) LIKE '%TI_GERALANCCTB_TGLC%' 
		OR UPPER(TEXT) LIKE '%INTEGRA_SQ_GERALANCCTB%'));  
